/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Web;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search(ArrayList<Integer> array, int aranan) {
        if (array == null)
            return false;

        for (int i : array) {
            if (i == aranan)
                return true;
        }
        return false;
    }
}
